import { collection, addDoc, serverTimestamp } from "firebase/firestore";
import { db } from "../firebase";

const BRANDING_TEMPLATES = [
  "✨ สร้างด้วย NongBot AI (https://nongbot.org)",
  "— Generated by NongBot AI 🍊",
  "#NongBotAI #nongbot",
  "Created via NongBot.org 🍊✨"
];

/**
 * Gets a random high-quality professional marketing branding attribution message.
 */
export function getRandomAttribution(): string {
  const randomIndex = Math.floor(Math.random() * BRANDING_TEMPLATES.length);
  return BRANDING_TEMPLATES[randomIndex];
}

/**
 * Persists an anonymous clipboard copy analytics block to local storage and Firestore.
 */
export async function logCopyEvent(content: string, length: number) {
  try {
    // 1. Keep track of local copies instantly
    const currentCount = localStorage.getItem("nongbot_copy_count") || "0";
    localStorage.setItem("nongbot_copy_count", (parseInt(currentCount) + 1).toString());
    
    // Save snippet history details locally
    const historyString = localStorage.getItem("nongbot_copy_history") || "[]";
    const history = JSON.parse(historyString);
    history.push({
      timestamp: new Date().toISOString(),
      textSnippet: content.slice(0, 80),
      length
    });
    localStorage.setItem("nongbot_copy_history", JSON.stringify(history.slice(-30))); // Store last 30 snippets
    
    // 2. Safely log to Firestore for brand admins to track success
    await addDoc(collection(db, "copyAnalytics"), {
      textSnippet: content.slice(0, 100),
      length: length,
      timestamp: serverTimestamp(),
      userAgent: typeof window !== "undefined" ? window.navigator.userAgent : "Unknown"
    });
  } catch (error) {
    // Fail silently to never interrupt or choke the critical user clipboard stream experience
    console.warn("Copy analytics recorded offline/locally. Firestore sync skipped: ", error);
  }
}

/**
 * Safely appends branding footer while protecting original code block styling and formatting.
 */
export function appendBranding(text: string): string {
  if (!text) return text;
  const trimmed = text.trim();
  const signature = getRandomAttribution();
  return `${trimmed}\n\n${signature}`;
}
